<?php require(BASE_PATH . '/templates/partials/admin_header.php') ?>

    <div class="content-header">
        <h1>Yeni Etiket Ekle</h1>
        <a href="/admin/tags" class="button">
            <i data-lucide="arrow-left"></i>
            <span>Geri Dön</span>
        </a>
    </div>

    <div class="content-panel">
        <form method="POST" action="/admin/tags" class="form">
            <input type="hidden" name="csrf_token" value="<?= $_SESSION['csrf_token'] ?>">
            
            <div class="form-group">
                <label for="name">Etiket Adı *</label>
                <input 
                    type="text" 
                    id="name" 
                    name="name" 
                    class="form-control <?= isset($_SESSION['errors']['name']) ? 'error' : '' ?>"
                    value="<?= htmlspecialchars($_SESSION['old']['name'] ?? '') ?>"
                    required
                    placeholder="Örn: PHP"
                >
                <?php if (isset($_SESSION['errors']['name'])): ?>
                    <span class="error-message"><?= $_SESSION['errors']['name'] ?></span>
                <?php endif; ?>
            </div>

            <div class="form-group">
                <label for="slug">Slug *</label>
                <input 
                    type="text" 
                    id="slug" 
                    name="slug" 
                    class="form-control <?= isset($_SESSION['errors']['slug']) ? 'error' : '' ?>"
                    value="<?= htmlspecialchars($_SESSION['old']['slug'] ?? '') ?>"
                    required
                    placeholder="Örn: php"
                    pattern="[a-z0-9-]+"
                    title="Sadece küçük harf, rakam ve tire kullanabilirsiniz"
                >
                <small class="form-help">Sadece küçük harf, rakam ve tire kullanın. Örn: php</small>
                <?php if (isset($_SESSION['errors']['slug'])): ?>
                    <span class="error-message"><?= $_SESSION['errors']['slug'] ?></span>
                <?php endif; ?>
            </div>

            <div class="form-group">
                <label for="description">Açıklama</label>
                <textarea 
                    id="description" 
                    name="description" 
                    class="form-control"
                    rows="3"
                    placeholder="Etiket hakkında kısa bir açıklama (opsiyonel)"
                ><?= htmlspecialchars($_SESSION['old']['description'] ?? '') ?></textarea>
                <small class="form-help">Bu açıklama etiket sayfasında görüntülenecektir.</small>
            </div>

            <div class="form-actions">
                <button type="submit" class="button button-primary">
                    <i data-lucide="save"></i>
                    <span>Etiket Ekle</span>
                </button>
                <a href="/admin/tags" class="button">İptal</a>
            </div>
        </form>
    </div>

    <script>
        // Etiket adından otomatik slug oluştur
        document.getElementById('name').addEventListener('input', function(e) {
            const slugInput = document.getElementById('slug');
            if (!slugInput.value || slugInput.dataset.autoGenerated !== 'false') {
                const slug = turkishToSlug(e.target.value);
                slugInput.value = slug;
                slugInput.dataset.autoGenerated = 'true';
            }
        });

        document.getElementById('slug').addEventListener('input', function(e) {
            this.dataset.autoGenerated = 'false';
        });

        function turkishToSlug(text) {
            const trMap = {
                'ğ': 'g', 'Ğ': 'g',
                'ü': 'u', 'Ü': 'u',
                'ş': 's', 'Ş': 's',
                'ı': 'i', 'İ': 'i',
                'ö': 'o', 'Ö': 'o',
                'ç': 'c', 'Ç': 'c'
            };

            return text
                .split('')
                .map(char => trMap[char] || char)
                .join('')
                .toLowerCase()
                .replace(/[^a-z0-9]+/g, '-')
                .replace(/^-+|-+$/g, '');
        }
    </script>

<?php 
    unset($_SESSION['errors']);
    unset($_SESSION['old']);
?>

<?php require(BASE_PATH . '/templates/partials/admin_footer.php') ?>
